binder_test - fix an atest aborting exception in stoi("")
The failure is:
  I/ModuleListener: [16/57] BinderTest#GetSetProcSysNet fail:
  No test results.
  system/netd/tests/binder_test.cpp:973: Failure
  Value of: mNetd->getProcSysNet(ipversion, category, tun, parameter, &value).isOk()
  Actual: false
  Expected: true
  system/netd/tests/binder_test.cpp:974: Failure
  Value of: value.empty()
  Actual: true
  Expected: false
  terminating with uncaught exception of type std::invalid_argument: stoi: no conversion

  AtestTradefedTestRunner
  -----------------------
  Runner encountered a critical failure. Skipping.
  FAILURE: Traceback (most recent call last):
    ...
  EventHandleError: Error: Saw TEST_MODULE_STARTED Start event and TEST_RUN_ENDED End event. These should be equal!

Test: ran tests

Bug: 131268436
Signed-off-by: Maciej Żenczykowski <maze@google.com>
Change-Id: I6de1be8321e1112b8dbec01170db905b814c06e9
Merged-In: I6de1be8321e1112b8dbec01170db905b814c06e9
(cherry picked from commit 7b789b950b778c242ea8bf08325a49220fb8a9a5)